// Live model catalog: derives the model -> agent map from the installed
// Freebuff/Codebuff CLI binary instead of a hand-maintained static table.
//
// Freebuff does not expose a "list models" HTTP endpoint — the authoritative
// catalog ships inside the CLI itself (minified JS baking model-id constants
// and the agent tier maps). Upgrading the CLI updates the catalog, so reading
// it at runtime means the gateway NEVER falls behind Freebuff's releases.
//
// Tier selection: the CLI publishes two generations — base2 (legacy) and
// base3 (current/unlimited-premium). Base2 is retired per-model over time
// (e.g. base2-free-luna -> free_mode_legacy_luna_agent). Default to base3,
// which is the premium tier reached through the configured PROXY_URL.
//
// The catalog is cached (default 6h TTL), written to a JSON next to the
// gateway, and can be force-refreshed via an admin endpoint. If parsing
// fails or no CLI is found, it falls back to a minimal seed map kept only
// as an offline last resort.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { manicodeDir, ROOT_DIR } from './config.js';
import { currentCliVersion } from './http-client.js';

// A few online standbys as an offline fallback if the CLI can't be read.
const SEED = {
  'deepseek/deepseek-v4-flash': 'base3-free-deepseek-flash',
  'mimo/mimo-v2.5': 'base3-free-mimo',
  'minimax/minimax-m3': 'base3-free-minimax-m3',
  'openai/gpt-5.6-luna': 'base3-free-luna',
  'z-ai/glm-5.2': 'base3-free-glm',
};

const defaultCachePath = () => path.join(ROOT_DIR, 'catalog.cache.json');
const DEFAULT_TIER = 'base3'; // premium/unlimited tier (via proxy)

function cliCandidates() {
  const dir = manicodeDir();
  // Modern Freebuff, then legacy Codebuff binary; both carry the same maps.
  return [
    path.join(dir, 'freebuff.exe'),
    path.join(dir, 'codebuff.exe'),
  ];
}

/**
 * Parse the CLI binary bytes into { model -> agent } preferring `tier`.
 *
 * Strategy: scan for self-describing agent records generated by the bundle,
 * of the shape
 *     "base3-free-mimo":{publisher:"codebuff",model:"mimo/mimo-v2.5",...}
 * (the key may or may not be quoted). Each record directly ties an agent id
 * to its model id in one place — no reliance on the minified allocator's
 * variable names, which are unstable across bundles. Only the chosen tier's
 * agents become the live map; the pair with that agent also supplies its
 * OpenRouter/omnipresent model id.
 *
 * Returns null when the parse doesn't yield a usable map.
 */
export function parseCatalogFromBinary(filePath, tier = DEFAULT_TIER) {
  let data;
  try {
    data = fs.readFileSync(filePath, 'latin1');
  } catch {
    return null;
  }

  const prefix = `${tier}-free-`; // e.g. "base3-free-"
  // 1) Self-describing agent records:  "base3-free-mimo":{publisher:"codebuff",model:"mimo/v2.5",…}
  //    Directly tie agent -> model in one place (reliable across bundle renames).
  const agentRe = /"(base[23]-free-[a-z0-9._-]+)"\s*:\s*\{publisher\s*:\s*"codebuff"\s*,\s*model\s*:\s*"([a-zA-Z0-9._/-]+)"/g;
  const agentsByModel = new Map(); // model -> Set(agent ids of all tiers)
  let m;
  while ((m = agentRe.exec(data)) !== null) {
    const [, agent, model] = m;
    if (!model.includes('/') || model.startsWith('http')) continue;
    if (!agentsByModel.has(model)) agentsByModel.set(model, new Set());
    agentsByModel.get(model).add(agent);
  }

  // Pick per model the agent matching the chosen tier. A model can be published
  // under several peers of a tier (root, -evals, -max, …); prefer the ROOT agent
  // (fewest path segments), so deepseek-flash -> base3-free-deepseek-flash, not
  // the -evals roll.
  const tiered = {};
  for (const [model, agents] of agentsByModel) {
    const cands = [...agents].filter((a) => a.startsWith(prefix));
    if (!cands.length) continue;
    cands.sort((a, b) => a.length - b.length); // root id is the shortest
    tiered[model] = cands[0];
  }

  // 2) Extended variants not emitted as standalone codebuff-publisher records
  //    (e.g. openai/gpt-5.6-luna-es / -max, muse-spark) live only in the
  //    minified model-var maps. Recover them and keep the ones whose resolved
  //    agent is on this tier, without overriding a strong record.
  const modelVars = new Map(); // var -> model
  const reModel = /([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*"([a-zA-Z0-9._/-]+)"/g;
  while ((m = reModel.exec(data)) !== null) {
    const [, varName, val] = m;
    if (val.includes('/') && !val.startsWith('http')) modelVars.set(varName, val);
  }
  const pairRe = new RegExp(`\\[([A-Za-z_$][A-Za-z0-9_$]*)\\]\\s*:\\s*"(${tier}-free-[a-z0-9._-]+)"`, 'g');
  while ((m = pairRe.exec(data)) !== null) {
    const [, varName, agent] = m;
    const model = modelVars.get(varName);
    if (model && !Object.prototype.hasOwnProperty.call(tiered, model)) tiered[model] = agent;
  }

  return Object.keys(tiered).length ? tiered : null;
}

export function readCliCatalog(tier = DEFAULT_TIER) {
  for (const p of cliCandidates()) {
    const map = parseCatalogFromBinary(p, tier);
    if (map) return { map, source: p };
  }
  return null;
}

function readCache(cachePath) {
  try {
    const raw = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
    if (raw && typeof raw === 'object' && raw.models && raw.updatedAt) return raw;
  } catch { /* corrupt or absent */ }
  return null;
}

function writeCache(catalog, cachePath) {
  try {
    fs.writeFileSync(cachePath, JSON.stringify({ updatedAt: Date.now(), models: catalog }, null, 2));
  } catch { /* non-fatal */ }
}

/**
 * Live catalog loader. Priority — freshness first when the CLI exists:
 *   1. parse the installed CLI (the live source of truth; persisted to cache)
 *   2. on-disk cache (fresh OR stale) as an offline fallback
 *   3. bundled SEED (last resort)
 * The cache is never preferred over a live read, so a restart can't pin a
 * stale catalog (a common failure with hand-rolled caches — e.g. a model
 * added in an earlier session lingering after Freebuff retires it).
 * Returns { updatedAt, source, models } where models is { id -> agent }.
 */
export function loadCatalog({ tier = DEFAULT_TIER, cachePath = defaultCachePath(), ttlMs = 6 * 3600 * 1000 } = {}) {
  const cli = readCliCatalog(tier);
  if (cli) {
    writeCache(cli.map, cachePath);
    return { updatedAt: Date.now(), source: cli.source, models: cli.map };
  }

  // No CLI readable — fall back to the cache regardless of age, then seed.
  const cached = readCache(cachePath);
  if (cached && cached.models) {
    return { updatedAt: cached.updatedAt, source: 'cache', models: cached.models };
  }
  return { updatedAt: Date.now(), source: 'seed', models: { ...SEED } };
}

export function refreshStatistics(catalog) {
  return {
    source: catalog.source,
    updatedAt: catalog.updatedAt,
    cli: currentCliVersion(),
    models: Object.keys(catalog.models).length,
  };
}

// Deterministic import-path helper for server.js status output
export function catalogSourceLabel(catalog) {
  return catalog.source;
}